# Generated by Django 5.1.4 on 2024-12-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiView', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='thought',
        ),
        migrations.RemoveField(
            model_name='user',
            name='time',
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
