# Generated by Django 5.1.4 on 2024-12-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiView', '0002_remove_user_thought_remove_user_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
